# Generated by Django 4.1.7 on 2023-03-31 20:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='satisfied customer', max_length=255, verbose_name=django.contrib.auth.models.User),
        ),
    ]
