# Generated by Django 4.1.7 on 2023-04-25 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0013_remove_orderitem_discount_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('order_number', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_name', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.discount')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='orders.order')),
            ],
        ),
    ]
