# Generated by Django 4.1.7 on 2023-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_category_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='item',
            name='cats',
            field=models.ManyToManyField(related_name='category', to='items.category'),
        ),
    ]
