# Generated by Django 4.1.7 on 2023-03-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_category_options_item_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cats',
            field=models.ManyToManyField(null=True, related_name='category', to='items.category'),
        ),
    ]
