# Generated by Django 4.1.7 on 2023-03-29 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_cats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=255)),
                ('order_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_name', 'order_number')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('order_number', models.IntegerField()),
                ('ItemPrice', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.SmallIntegerField()),
                ('DiscountPrice', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Discount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.discount')),
                ('Item_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.order')),
            ],
        ),
    ]
