# Generated by Django 4.1.7 on 2023-03-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_order_item_price_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cats',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_number',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category', to='items.category'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
