# Generated by Django 4.1.7 on 2023-03-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_rename_discount_orderitem_discount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(default='ASDF', max_length=30),
            preserve_default=False,
        ),
    ]
