# Generated by Django 4.1.7 on 2023-04-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_category_image_item_image_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
