# Generated by Django 4.1.7 on 2023-05-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(choices=[('COIN', 'Valheim gold coin'), ('DOGE', 'Dogecoin'), ('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='COIN', max_length=16, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('units', models.IntegerField(default=1)),
            ],
        ),
    ]
