# Generated by Django 4.1.7 on 2023-05-02 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('COIN', 'Valheim gold coin'), ('DOGE', 'Dogecoin'), ('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('units', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
