# Generated by Django 4.1.7 on 2023-05-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_currencyhistory_currency_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyHistory',
        ),
    ]
