name: flake8

on: 
  push:
    branches: [ django ]
  pull_request:
    branches: [ django ]


jobs:
  flake8:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run flake8
      run: |
        flake8 .
